# Generated by Django 4.2.11 on 2024-09-18 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('temaProfessor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_jogo', models.DateTimeField(auto_now_add=True)),
                ('acertos', models.ManyToManyField(blank=True, related_name='acertos', to='jogo.letra')),
                ('erros', models.ManyToManyField(blank=True, related_name='erros', to='jogo.letra')),
                ('jogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('palavra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temaProfessor.palavra')),
            ],
        ),
    ]
