# Generated by Django 4.2.11 on 2024-09-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_tema_estar_logado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='nome_anonimo',
        ),
    ]
