# Generated by Django 4.2.11 on 2024-09-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temaProfessor', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='palavra',
            constraint=models.UniqueConstraint(fields=('tema', 'palavra'), name='unique_palavra_tema'),
        ),
    ]
